resilience4j.circuitbreaker:
    configs:
        default:
            slidingWindowSize: 100
            permittedNumberOfCallsInHalfOpenState: 5
            waitDurationInOpenState: 10000
            failureRateThreshold: 60
            eventConsumerBufferSize: 10
            registerHealthIndicator: true
            record-exceptions:
             - java.lang.Exception
    instances:
       backendA:
            baseConfig: default
            waitDurationInOpenState: 5000
       backendB:
            baseConfig: default
            waitDurationInOpenState: 5000
            
eureka:
   client:
      serviceUrl:
         defaultZone: http://localhost:8761/eureka
   instance:
    prefer-ip-address: true
    
    
management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always